version: "3.7"
services:

  ##########
  # Download image
  ##########
  ibm-openapi-validator:
    build:
      context: .
      args:
        VERSION: v0.15.1
      dockerfile: Dockerfile
    image: index.docker.io/dkirrane/ibm-openapi-validator:v0.15.1
